In [2]:
import hashlib
import requests
import datetime
import pandas as pd
timestamp = datetime.datetime.now().strftime('%Y-%m-%d%H:%M:%S')
def hash_params():
    """ Marvel API requires server side API calls to include
    md5 hash of timestamp + public key + private key """

    hash_md5 = hashlib.md5()
    hash_md5.update(f'{timestamp}{priv_key}{pub_key}'.encode('utf-8'))
    hashed_params = hash_md5.hexdigest()
    hp=hashed_params

    return hp

def my_function(pub_key,hash,ts,name):
    df_new=pd.DataFrame()
    for i in range(0,4):
        lt=20
        params = {'ts': ts, 'apikey': pub_key, 'hash': hash,'limit':lt,'nameStartsWith':name,'limit':100,'offset': 100*i}
        res = requests.get('https://gateway.marvel.com:443/v1/public/characters',params=params)
        
        if(res.status_code != 200):
            print(res.status_code,res.reason)
            raise Exception(res.reason)
            
        call = res.json()
        da=(call['data']['results'])
        df1=pd.json_normalize(da)
        df_new=df_new.append(df1)
    df2=df_new[['name','events.available','series.returned','stories.available','comics.available','id']]
    return df2
pub_key=input('Enter the API or public key : ')
priv_key =input('Enter the private key : ')
namestarting=input()   
my_function(pub_key,hash_params(),timestamp,namestarting)

C:\Users\Harsh\AppData\Local\Temp\ipykernel_22548\1904617321.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new=df_new.append(df1)

,name,events.available,series.returned,stories.available,comics.available,id
0,Spider-dok,0,0,0,0,1010727
1,Spider-Girl (Anya Corazon),2,18,77,68,1009157
2,Spider-Girl (May Parker),1,20,309,196,1009609
3,Spider-Gwen (Gwen Stacy),2,20,134,131,1017603
4,Spider-Ham (Larval Earth),0,20,53,52,1011347
5,Spider-Man (1602),0,5,79,44,1011054
6,Spider-Man (2099),0,20,66,66,1014873
7,Spider-Man (Ai Apaec),0,2,29,15,1016452
8,Spider-Man (Ben Reilly),1,20,66,65,1014858
9,Spider-Man (House of M),0,0,0,0,1012200
10,Spider-Man (LEGO Marvel Super Heroes),0,0,0,0,1017332
11,Spider-Man (Marvel Zombies),0,4,8,8,1011114
12,Spider-Man (Marvel: Avengers Alliance),0,0,0,0,1017305
13,Spider-Man (Miles Morales),2,20,353,341,1016181
14,Spider-Man (Noir),0,6,17,16,1012295
15,Spider-Man (Peter Parker),38,20,6159,4167,1009610
16,Spider-Man (Takuya Yamashiro),0,0,0,0,1011377
17,Spider-Man (Ultimate),0,20,351,260,1011010
18,Spider-Woman (Charlotte Witter),1,6,14,11,1010795
19,Spider-Woman (Jessica Drew),14,20,301,288,1009608
20,Spider-Woman (Mattie Franklin),1,5,16,16,1010794

In [35]:
def filter(df,column,filt):
    temp_list=filt.split()
    num_list=[]
    for i in temp_list:
        if i.isdigit()==True:
            num_list.append(i)

    if ('greater' in filt):
        df_new=df.loc[df[column]>=int(num_list[0]),['id','name']]
    else:
        df_new=df.loc[df[column]<=int(num_list[0]),['id','name']]
        
    return df_new
filter(my_function(pub_key,hash_params(),timestamp,namestarting),'stories.available','less than 40')

C:\Users\Harsh\AppData\Local\Temp\ipykernel_22548\1904617321.py:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new=df_new.append(df1)

         id                                    name
0   1010727                              Spider-dok
7   1016452                   Spider-Man (Ai Apaec)
9   1012200                 Spider-Man (House of M)
10  1017332   Spider-Man (LEGO Marvel Super Heroes)
11  1011114             Spider-Man (Marvel Zombies)
12  1017305  Spider-Man (Marvel: Avengers Alliance)
14  1012295                       Spider-Man (Noir)
16  1011377           Spider-Man (Takuya Yamashiro)
18  1010795         Spider-Woman (Charlotte Witter)
20  1010794          Spider-Woman (Mattie Franklin)

In [32]:
filt= 'greater than 20'
if 'greater' in filt:
    print('greater present')
temp_list=filt.split()
num_list=[]
for i in temp_list:
    if i.isdigit()==True:
        num_list.append(i)
num_list[0]

greater present

'20'